import type { LandingConfig, LandingBlock } from '@/types/landing'
import {
  type HeroProductData,
  type TikTokCommentsData,
  type BeforeAfterData,
  type FeaturedProductData,
  type FAQData,
  type CTAData,
} from '@/types/landing'

// ─── TikTok Product ───────────────────────────────────────────────────────────
function makeTikTokProductBlocks(): LandingBlock[] {
  return [
    {
      id: 'tp_hero',
      type: 'hero_product',
      label: 'Hero',
      visible: true,
      data: {
        headline: 'The Product Everyone on TikTok Is Talking About',
        subheadline: 'Clinically proven formula · Visible results in 7 days',
        description: 'Join over 2M people who\'ve already transformed their routine. Backed by science, loved by creators.',
        imageUrl: '',
        badgeText: '#1 Product on TikTok 🔥',
        showBadge: true,
        showRating: true,
        rating: '4.9',
      } satisfies HeroProductData,
    },
    {
      id: 'tp_tiktok_comments',
      type: 'tiktok_comments',
      label: 'TikTok Comments',
      visible: true,
      data: {
        title: '',
        subtitle: '',
        badgeText: '',
        showTitle: false,
        showSubtitle: false,
        showBadge: false,
        layout: 'carousel',
        comments: [
          {
            id: 'tc1',
            avatarUrl: '',
            username: 'Sofia.wellness 🌿',
            verified: false,
            text: 'Okay I\'ve been using this for 3 weeks and my skin literally looks different. My mom asked if I got a facial 😭 the texture improvement alone is worth it, I wasn\'t expecting results this fast tbh',
            imageUrl: '',
            likes: '18.4K',
            date: '2 d',
            replyItems: [
              {
                id: 'r1a',
                avatarUrl: '',
                username: 'Official Brand ✨',
                verified: true,
                text: 'That makes us SO happy to hear! 3 weeks is right when most customers start seeing major results 💗 Thank you for sharing!',
                likes: '342',
                date: '1 d',
              },
            ],
            showReply: true,
            showLikes: true,
            showReplies: true,
          },
          {
            id: 'tc2',
            avatarUrl: '',
            username: 'realgirlreviews',
            verified: true,
            text: 'I was super skeptical bc I\'ve tried everything for my hyperpigmentation. This is literally the first product that has made a visible difference in my dark spots. I\'m genuinely shocked and I don\'t say that lightly',
            imageUrl: '',
            likes: '42.1K',
            date: '5 d',
            replyItems: [
              {
                id: 'r2a',
                avatarUrl: '',
                username: 'Maya_skincare',
                verified: false,
                text: 'Same!!! I had the same experience, been using it for a month and the results are unreal 🙌',
                likes: '1.2K',
                date: '4 d',
              },
              {
                id: 'r2b',
                avatarUrl: '',
                username: 'Official Brand ✨',
                verified: true,
                text: 'Hyperpigmentation is one of our specialty formulas! So glad it\'s working for you 💕',
                likes: '890',
                date: '4 d',
              },
            ],
            showReply: true,
            showLikes: true,
            showReplies: true,
          },
          {
            id: 'tc3',
            avatarUrl: '',
            username: 'tiktokbymartina',
            verified: false,
            text: 'The way this arrived in 2 days and I was already using it the same night 😂 I\'ve been doing updates every 3 days and the difference is genuinely insane. Already ordered the full size before finishing the trial',
            imageUrl: '',
            likes: '9.2K',
            date: '1 sem',
            replyItems: [
              {
                id: 'r3a',
                avatarUrl: '',
                username: 'Official Brand ✨',
                verified: true,
                text: 'Love the dedication! 3-day updates are the best way to track progress 📈',
                likes: '156',
                date: '6 d',
              },
            ],
            showReply: true,
            showLikes: true,
            showReplies: true,
          },
        ],
        showArrows: true,
        showDots: true,
        autoplay: false,
        autoplaySpeed: 3,
        borderRadius: 'soft',
        shadowIntensity: 'soft',
        spacing: 'normal',
      } satisfies TikTokCommentsData,
    },
    {
      id: 'tp_before_after',
      type: 'before_after',
      label: 'Before / After',
      visible: true,
      data: {
        title: 'See The Difference',
        subtitle: 'Real results from real customers after consistent use.',
        badgeText: 'Verified Results ✓',
        mode: 'cards',
        beforeImageUrl: '',
        afterImageUrl: '',
        beforeLabel: 'Before',
        afterLabel: 'After',
        beforeDescription: 'Dull skin, uneven texture, visible dark spots after years of sun damage and stress.',
        afterDescription: 'Radiant, smooth skin with visibly reduced dark spots in just 28 days of daily use.',
        showBadge: true,
        showSubtitle: true,
        showDescriptions: true,
        showCTA: false,
        buttonText: 'View Official Product',
        buttonUrl: '',
        borderRadius: 'soft',
        shadowIntensity: 'soft',
      } satisfies BeforeAfterData,
    },
    {
      id: 'tp_featured_product',
      type: 'featured_product',
      label: 'Product Showcase',
      visible: true,
      data: {
        imageUrl: '',
        badgeText: 'Most Loved 🔥',
        productName: 'Why You\'ll Love It',
        description: 'Every ingredient is chosen for maximum efficacy. No fillers, no compromises — just results you can see.',
        rating: 4.9,
        reviewCount: '2.4K',
        price: '$29.99',
        compareAtPrice: '$49.99',
        discountText: '-40%',
        benefits: [
          'Clinically tested formula with dermatologist approval',
          '100% clean ingredients, cruelty-free & vegan',
          'Visible improvement from first application',
          'Made for all skin tones and types',
        ],
        buttonText: 'View Official Product',
        buttonUrl: '',
        showBadge: true,
        showRating: true,
        showReviews: true,
        showPrice: true,
        showCompareAtPrice: true,
        showDiscount: true,
        showBenefits: true,
        layout: 'card',
        colorTheme: 'dark',
        buttonStyle: 'filled',
      } satisfies FeaturedProductData,
    },
    {
      id: 'tp_faq',
      type: 'faq',
      label: 'FAQ',
      visible: true,
      data: {
        title: 'Frequently Asked Questions',
        items: [
          {
            id: 'faq1',
            question: 'How fast will I see results?',
            answer: 'Most customers notice a visible difference within 7–14 days of consistent daily use. Full results are typically visible after 28 days. For best results, use every morning and evening on clean skin.',
          },
          {
            id: 'faq2',
            question: 'Is it safe for sensitive skin?',
            answer: 'Yes! Our formula is dermatologist-tested and free from parabens, sulfates, and artificial fragrances. It\'s suitable for all skin types including sensitive skin. We recommend a patch test before full application.',
          },
          {
            id: 'faq3',
            question: 'What\'s your return policy?',
            answer: 'We offer a 30-day no-questions-asked money-back guarantee. If you\'re not completely satisfied with your results, contact our support team for a full refund. We stand behind our product 100%.',
          },
          {
            id: 'faq4',
            question: 'Do you ship internationally?',
            answer: 'We currently ship to the US, Canada, UK, EU, and Australia. Standard shipping takes 3–7 business days. Free shipping on all orders over $30. Express delivery available at checkout.',
          },
        ],
      } satisfies FAQData,
    },
    {
      id: 'tp_cta',
      type: 'cta',
      label: 'Final CTA',
      visible: true,
      data: {
        text: '🛒 View Official Product',
        subtext: 'Join thousands of happy customers.',
        url: '',
        style: 'gradient',
      } satisfies CTAData,
    },
  ]
}

export function getTemplateConfig(
  templateId: string,
  overrides: { id?: string; title?: string; slug?: string; status?: 'draft' | 'published' },
): LandingConfig | null {
  switch (templateId) {
    case 'tiktok-product':
      return {
        id: overrides.id,
        title: overrides.title ?? 'TikTok Product',
        slug: overrides.slug ?? 'tiktok-product',
        status: overrides.status ?? 'draft',
        destinationUrl: '',
        template: 'trust_product',
        theme: {
          primaryColor: '#FF2D55',
          secondaryColor: '#8B5CF6',
          backgroundColor: '#0B0B12',
          textColor: '#FFFFFF',
          fontFamily: 'Inter',
          radius: 'soft',
          backgroundMode: 'solid',
          accentColor: '#FF4D6A',
          secondaryTextColor: '#A1A1AA',
          cardBackgroundColor: '#18181F',
          elementBackgroundColor: '#252530',
          borderColor: '#2E2E3A',
          buttonTextColor: '#FFFFFF',
          buttonStyle: 'gradient',
          buttonGradientFrom: '#FF2D55',
          buttonGradientTo: '#8B5CF6',
        },
        settings: {
          showTokproofBranding: true,
          enableTikTokRescue: false,
          directExitUrl: '',
          seoTitle: overrides.title ?? 'TikTok Product',
          seoDescription: '',
        },
        blocks: makeTikTokProductBlocks(),
      }
    default:
      return null
  }
}
